import { toOpenApiPath } from '../analyze/url-utils.js';

/**
 * @param {import('../models.js').EndpointFinding[]} findings
 * @param {{ baseUrl: URL, title?: string }} opts
 */
export function toOpenApi(findings, { baseUrl, title }) {
  /** @type {Record<string, any>} */
  const paths = {};
  /** @type {Array<object>} */
  const graphqlOps = [];
  /** @type {string[]} */
  const websockets = [];

  for (const f of findings) {
    if (f.websocket) {
      websockets.push(f.url);
      continue;
    }
    if (f.graphql) {
      graphqlOps.push({
        operationName: f.graphql.operationName,
        operationType: f.graphql.operationType,
        path: f.pathTemplate,
      });
    }

    const pathKey = toOpenApiPath(
      f.pathTemplate?.startsWith('/')
        ? f.pathTemplate
        : (() => {
            try {
              return new URL(f.url, baseUrl).pathname;
            } catch {
              return f.pathTemplate || '/';
            }
          })(),
    );

    const method = (f.method || 'get').toLowerCase();
    if (!paths[pathKey]) paths[pathKey] = {};

    const parameters = [];
    for (const m of pathKey.matchAll(/\{([^}]+)\}/g)) {
      parameters.push({
        name: m[1],
        in: 'path',
        required: true,
        schema: { type: 'string' },
      });
    }
    for (const q of f.queryParams || []) {
      parameters.push({
        name: q,
        in: 'query',
        required: false,
        schema: { type: 'string' },
      });
    }

    /** @type {Record<string, any>} */
    const op = {
      summary: f.graphql?.operationName || `${method.toUpperCase()} ${pathKey}`,
      parameters,
      responses: {
        200: { description: 'Observed or inferred by ChunkSpelunker' },
      },
    };

    if (f.sse) op['x-sse'] = true;
    if (f.bodyParams?.length) {
      const props = {};
      for (const k of f.bodyParams) props[k] = { type: 'string' };
      op.requestBody = {
        content: {
          'application/json': {
            schema: { type: 'object', properties: props },
          },
        },
      };
    }

    // Don't overwrite existing method unless missing
    if (!paths[pathKey][method]) paths[pathKey][method] = op;
  }

  if (graphqlOps.length) {
    const gqlPath = Object.keys(paths).find((p) => /graphql|gql/i.test(p)) || '/graphql';
    if (!paths[gqlPath]) paths[gqlPath] = {};
    const post = paths[gqlPath].post || {
      summary: 'GraphQL endpoint',
      responses: { 200: { description: 'GraphQL' } },
    };
    post['x-graphql-operations'] = graphqlOps;
    paths[gqlPath].post = post;
  }

  return {
    openapi: '3.0.3',
    info: {
      title: title || `ChunkSpelunker — ${baseUrl.hostname}`,
      version: '1.0.0',
      description: 'Auto-generated by ChunkSpelunker',
    },
    servers: [{ url: baseUrl.origin }],
    paths,
    ...(websockets.length ? { 'x-websockets': websockets } : {}),
  };
}
