import { toOpenApiPath } from '../analyze/url-utils.js';

/**
 * @param {import('../models.js').EndpointFinding[]} findings
 * @param {{ baseUrl: URL, title?: string }} opts
 */
export function toPostman(findings, { baseUrl, title }) {
  const items = findings.map((f) => {
    const name = f.graphql?.operationName
      ? `GQL ${f.graphql.operationType || 'op'} ${f.graphql.operationName}`
      : f.websocket
        ? `WS ${f.pathTemplate || f.url}`
        : f.sse
          ? `SSE ${f.pathTemplate || f.url}`
          : `${f.method} ${f.pathTemplate || f.url}`;

    let absUrl;
    try {
      absUrl = new URL(f.url || f.pathTemplate || '/', baseUrl);
    } catch {
      try {
        absUrl = new URL(String(f.pathTemplate || '/').replace(/[{}]/g, ''), baseUrl);
      } catch {
        absUrl = new URL('/', baseUrl);
      }
    }
    // Guard against template garbage that parses but is unusable
    if (!absUrl.hostname || /[{{}}\s]/.test(absUrl.hostname)) {
      absUrl = new URL('/', baseUrl);
    }

    const crossOrigin = absUrl.origin !== baseUrl.origin;
    const pathForParts = (f.pathTemplate?.startsWith('/')
      ? f.pathTemplate
      : absUrl.pathname) || '/';
    const pathParts = pathForParts.replace(/^\//, '').split('/').filter(Boolean);

    /** @type {object} */
    const request = {
      method: f.method || 'GET',
      header: Object.entries(f.headers || {}).map(([key, value]) => ({ key, value })),
      url: crossOrigin
        ? {
            raw: absUrl.href,
            protocol: absUrl.protocol.replace(':', ''),
            host: absUrl.hostname.split('.'),
            path: pathParts,
            query: (f.queryParams || []).map((key) => ({ key, value: '' })),
          }
        : {
            raw: `{{baseUrl}}${pathForParts.startsWith('/') ? pathForParts : `/${pathForParts}`}`,
            host: ['{{baseUrl}}'],
            path: pathParts,
            query: (f.queryParams || []).map((key) => ({ key, value: '' })),
          },
    };

    if (f.graphql) {
      request.body = {
        mode: 'raw',
        raw: JSON.stringify(
          {
            operationName: f.graphql.operationName || null,
            query: '',
            variables: {},
          },
          null,
          2,
        ),
        options: { raw: { language: 'json' } },
      };
    } else if (f.bodyParams?.length) {
      const body = {};
      for (const k of f.bodyParams) body[k] = '';
      request.body = {
        mode: 'raw',
        raw: JSON.stringify(body, null, 2),
        options: { raw: { language: 'json' } },
      };
    }

    return {
      name,
      request,
      description: [
        f.websocket ? 'WebSocket endpoint' : null,
        f.sse ? 'Server-Sent Events stream (do not buffer body)' : null,
        `source=${f.source} confidence=${f.confidence}`,
      ]
        .filter(Boolean)
        .join('\n'),
    };
  });

  return {
    info: {
      name: title || `ChunkSpelunker — ${baseUrl.hostname}`,
      description: 'Auto-generated by ChunkSpelunker',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    variable: [{ key: 'baseUrl', value: baseUrl.origin }],
    item: items,
  };
}
